// <auto-generated />
namespace AiCard.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class VipTotalWeekAmountRankAndTotalMonthAmountRank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VipTotalWeekAmountRankAndTotalMonthAmountRank));
        
        string IMigrationMetadata.Id
        {
            get { return "201811200752294_VipTotalWeekAmountRankAndTotalMonthAmountRank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
